# Extracted from: https://mtg.gamepedia.com/Template:List_of_Magic_sets

expansions:
    - "Aether Revolt"
    - "Alara Reborn"
    - "Alliances"
    - "Alpha (Limited Edition)"
    - "Amonkhet"
    - "Amonkhet Invocations"
    - "Anthologies"
    - "Antiquities"
    - "Apocalypse"
    - "Arabian Nights"
    - "Archenemy"
    - "Archenemy: Nicol Bolas"
    - "Avacyn Restored"
    - "Battlebond"
    - "Battle for Zendikar"
    - "Battle Royale"
    - "Beatdown"
    - "Beta (Limited Edition)"
    - "Betrayers of Kamigawa"
    - "Born of the Gods"
    - "Challenger Decks"
    - "Challenger Decks 2019"
    - "Champions of Kamigawa"
    - "Chronicles"
    - "Coldsnap"
    - "Commander"
    - "Commander's Arsenal"
    - "Commander 2013"
    - "Commander 2014"
    - "Commander 2015"
    - "Commander 2016"
    - "Commander 2017"
    - "Commander 2018"
    - "Commander 2019"
    - "Commander Anthology"
    - "Commander Anthology Volume II"
    - "Commander Theme Decks"
    - "Conflux"
    - "Conspiracy"
    - "Conspiracy: Take the Crown"
    - "Core Set 2019"
    - "Core Set 2020"
    - "Dark Ascension"
    - "Darksteel"
    - "Deck Builder's Toolkit"
    - "Deck Builder's Toolkit 2011"
    - "Deckmasters 2001"
    - "Dissension"
    - "Dominaria"
    - "Dragon's Maze"
    - "Dragons of Tarkir"
    - "Duel Decks: Ajani vs. Nicol Bolas"
    - "Duel Decks: Blessed vs. Cursed"
    - "Duel Decks: Divine vs. Demonic"
    - "Duel Decks: Elspeth vs. Kiora"
    - "Duel Decks: Elspeth vs. Tezzeret"
    - "Duel Decks: Elves vs. Goblins"
    - "Duel Decks: Elves vs. Inventors"
    - "Duel Decks: Garruk vs. Liliana"
    - "Duel Decks: Heroes vs. Monsters"
    - "Duel Decks: Izzet vs. Golgari"
    - "Duel Decks: Jace vs. Chandra"
    - "Duel Decks: Jace vs. Vraska"
    - "Duel Decks: Knights vs. Dragons"
    - "Duel Decks: Merfolk vs. Goblins"
    - "Duel Decks: Mind vs. Might"
    - "Duel Decks: Mirrodin Pure vs. New Phyrexia"
    - "Duel Decks: Nissa vs. Ob Nixilis"
    - "Duel Decks: Phyrexia vs. The Coalition"
    - "Duel Decks: Sorin vs. Tibalt"
    - "Duel Decks: Speed vs. Cunning"
    - "Duel Decks: Venser vs. Koth"
    - "Duel Decks: Zendikar vs. Eldrazi"
    - "Duel Decks Anthology"
    - "Duels of the Planeswalkers"
    - "Eighth Edition"
    - "Eldritch Moon"
    - "Eternal Masters"
    - "Eventide"
    - "Exodus"
    - "Explorers of Ixalan"
    - "Fallen Empires"
    - "Fate Reforged"
    - "Fifth Dawn"
    - "Fifth Edition"
    - "Fourth Edition"
    - "From the Vault: Angels"
    - "From the Vault: Annihilation"
    - "From the Vault: Dragons"
    - "From the Vault: Exiled"
    - "From the Vault: Legends"
    - "From the Vault: Lore"
    - "From the Vault: Realms"
    - "From the Vault: Relics"
    - "From the Vault: Transform"
    - "From the Vault: Twenty"
    - "Future Sight"
    - "Game Night"
    - "Gatecrash"
    - "Global Series: Jiang Yanggu & Mu Yanling"
    - "Guildpact"
    - "Guilds of Ravnica"
    - "Guilds of Ravnica Guild Kits"
    - "Guilds of Ravnica Mythic Edition"
    - "Homelands"
    - "Hour of Devastation"
    - "Ice Age"
    - "Iconic Masters"
    - "Innistrad"
    - "Invasion"
    - "Ixalan"
    - "Journey into Nyx"
    - "Judgment"
    - "Kaladesh"
    - "Kaladesh Inventions"
    - "Khans of Tarkir"
    - "Legendary Cube"
    - "Legends"
    - "Legions"
    - "Lorwyn"
    - "Magic 2010"
    - "Magic 2011"
    - "Magic 2012"
    - "Magic 2013"
    - "Magic 2014"
    - "Magic 2015"
    - "Magic Online Deck Series"
    - "Magic Origins"
    - "Masters 25"
    - "Masters Edition"
    - "Masters Edition II"
    - "Masters Edition III"
    - "Masters Edition IV"
    - "Mercadian Masques"
    - "Mirage"
    - "Mirrodin"
    - "Mirrodin Besieged"
    - "Modern Event Deck"
    - "Modern Horizons"
    - "Modern Masters"
    - "Modern Masters 2015"
    - "Modern Masters 2017"
    - "Momir Basic Event Deck"
    - "Morningtide"
    - "Nemesis"
    - "New Phyrexia"
    - "Ninth Edition"
    - "Oath of the Gatewatch"
    - "Odyssey"
    - "Onslaught"
    - "Planar Chaos"
    - "Planechase"
    - "Planechase 2012"
    - "Planechase Anthology"
    - "Planeshift"
    - "Portal"
    - "Portal Second Age"
    - "Portal Three Kingdoms"
    - "Premium Deck Series: Fire & Lightning"
    - "Premium Deck Series: Graveborn"
    - "Premium Deck Series: Slivers"
    - "Prophecy"
    - "Ravnica: City of Guilds"
    - "Ravnica Allegiance"
    - "Ravnica Allegiance Guild Kits"
    - "Ravnica Allegiance Mythic Edition"
    - "Renaissance"
    - "Return to Ravnica"
    - "Revised Edition"
    - "Rise of the Eldrazi"
    - "Rivals of Ixalan"
    - "Salvat 2005"
    - "Salvat 2011"
    - "Saviors of Kamigawa"
    - "Scars of Mirrodin"
    - "Scourge"
    - "Seventh Edition"
    - "Shadowmoor"
    - "Shadows over Innistrad"
    - "Shards of Alara"
    - "Signature Spellbook: Gideon"
    - "Signature Spellbook: Jace"
    - "Classic Sixth Edition"
    - "Spellslinger Starter Kit"
    - "Starter 1999"
    - "Starter 2000"
    - "Stronghold"
    - "Tempest"
    - "Tempest Remastered"
    - "Tenth Edition"
    - "The Dark"
    - "Theros"
    - "Throne of Eldraine"
    - "Time Spiral"
    - "Torment"
    - "Treasure Chests"
    - "Ultimate Masters"
    - "Unglued"
    - "Unhinged"
    - "Unlimited Edition"
    - "Unstable"
    - "Urza's Destiny"
    - "Urza's Legacy"
    - "Urza's Saga"
    - "Vintage Masters"
    - "Visions"
    - "War of the Spark"
    - "War of the Spark Mythic Edition"
    - "Weatherlight"
    - "Welcome Deck 2016"
    - "Welcome Deck 2017"
    - "Worldwake"
    - "You Make the Cube"
    - "Zendikar"
    - "Zendikar Expeditions"
